apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clickhouse
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_DB
              value: otel_logs
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
            - name: CLICKHOUSE_PASSWORD
              value: password
            - name: CLICKHOUSE_USER
              value: default
          image: clickhouse/clickhouse-server:latest
          livenessProbe:
            exec:
              command:
                - wget
                - --no-verbose
                - --tries=1
                - --spider
                - http://localhost:8123/ping
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          name: clickhouse
          ports:
            - containerPort: 8123
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: clickhouse-data
      restartPolicy: Always
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-data
