apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: clickhouse-data
  name: clickhouse-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
