apiVersion: v1
kind: Service
metadata:
  labels:
    app: clickhouse
  name: clickhouse
spec:
  ports:
    - name: "8123"
      port: 8123
      targetPort: 8123
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: clickhouse
