version: '3.8'

services:
    clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
            - '8123:8123' # HTTP interface
            - '9000:9000' # Native interface
        environment:
            CLICKHOUSE_DB: otel_logs
            CLICKHOUSE_USER: default
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
            CLICKHOUSE_PASSWORD: password
        volumes:
            - clickhouse-data:/var/lib/clickhouse
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:8123/ping',
                ]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 10s

    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        depends_on:
            clickhouse:
                condition: service_healthy
        ports:
            - '4317:4317' # OTLP gRPC
            - '4318:4318' # OTLP HTTP
            - '8888:8888' # Metrics
        volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        command: ['--config', '/etc/otel-collector-config.yaml']
        restart: unless-stopped

    express-app:
        build: .
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: development
            OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
            OTEL_SERVICE_NAME: express-app
        depends_on:
            otel-collector:
                condition: service_started

    superset:
        image: apache/superset:latest
        ports:
            - '8088:8088'
        environment:
            SUPERSET_SECRET_KEY: your-secret-key-here
            SUPERSET_LOAD_EXAMPLES: 'no'
        volumes:
            - superset-data:/app/superset_home
        depends_on:
            clickhouse:
                condition: service_healthy
        command: >
            bash -c "superset db upgrade &&
                    superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
                    superset init &&
                    superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"

volumes:
    clickhouse-data:
    superset-data:
