apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: express-app
  name: express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: development
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otel-collector:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: express-app
          image: leskis/otel-express-app
          name: express-app
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
