receivers:
    otlp:
        protocols:
            grpc:
                endpoint: '0.0.0.0:4317'
            http:
                endpoint: '0.0.0.0:4318'

processors:
    batch:
        timeout: 1s
        send_batch_size: 1024

exporters:
    clickhouse:
        endpoint: tcp://clickhouse:9000
        database: otel_logs
        username: default
        password: password
        timeout: 10s
        sending_queue:
            queue_size: 100
        retry_on_failure:
            enabled: true
            initial_interval: 1s
            max_interval: 5s
            max_elapsed_time: 30s

service:
    pipelines:
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [clickhouse]
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [clickhouse]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [clickhouse]

    telemetry:
        logs:
            level: 'debug'
        metrics:
            level: 'detailed'
            address: '0.0.0.0:8888'
